#Kun.Hu@TECH.BSP.Stability.PHOENIX_PROJECT 2019/06/15, Add for PHOENIX_PROJECT
ifeq ($(CONFIG_OPPO_PHOENIX),y)
obj-$(CONFIG_OPPO_PHOENIX) += op_bootprof.o
obj-$(CONFIG_OPPO_PHOENIX) += phoenix_base.o
obj-$(CONFIG_OPPO_PHOENIX) += phoenix_dump.o
obj-$(CONFIG_OPPO_PHOENIX) += phoenix_watchdog.o
endif
