obj-$(CONFIG_QIHOO) += verify.o
verify-objs :=					\
		generic_mpih-lshift.o		\
		generic_mpih-mul1.o		\
		generic_mpih-mul2.o		\
		generic_mpih-mul3.o		\
		generic_mpih-rshift.o		\
		generic_mpih-sub1.o		\
		generic_mpih-add1.o		\
		memneq.o			\
		mpiutil.o			\
		mpi-pow.o			\
		mpicoder.o			\
		mpi-bit.o			\
		mpi-cmp.o			\
		mpih-cmp.o			\
		mpih-mul.o			\
		mpih-div.o			\
		rsa.o				\
		hash_info.o			\
		public_key.o			\
		qh_sign_verify.o
