#ifdef VENDOR_EDIT
#//John.Xu@PhoneSw.AudioDriver.OppoDebug.CriticalLog, 2016/02/22, Add for critical_log
#obj-$(CONFIG_OPPO_CRITICALLOG)	+=  oppo_criticallog.o
#Xiaoshan.Huang
#obj-$(CONFIG_OPPO_CRITICALLOG)   +=  oppo_criticallog.o
#endif /* VENDOR_EDIT */

#ifdef VENDOR_EDIT
#//Xiaoshan.Huang@PSW.NW.EM, 2019/10/13, Add for critical_log
#obj-$(CONFIG_OPPO_CRITICALLOG)   +=  oppo_criticallog.o
obj-y  +=  oppo_criticallog.o criticallog_class.o
#endif /* VENDOR_EDIT */
