#ifdef VENDOR_EDIT
#xiang.fei@Multimedia.AudioDriver.Codec, 2018/03/12, add for codec
snd-soc-tfa98xx-v6-objs := tfa_container_v6.o tfa98xx_v6.o tfa_dsp_v6.o tfa_init_v6.o
obj-y += snd-soc-tfa98xx-v6.o
#endif /* VENDOR_EDIT */