
# Yongzhi.Zhang@PSW.MM.AudioDriver.SmartPA, 2017/10/07,
# add log for checking w/r reg
snd-soc-tfa98xx-objs := tfa98xx.o tfa_dsp.o tfa_container.o tfa9890_init.o tfa9891_init.o tfa9887_init.o tfa9887B_init.o tfa9888_init.o  tfa9897_init.o tfa_debug.o
obj-y += snd-soc-tfa98xx.o

